### ISSUE TITLE
Incorrect urls in css

### ISSUE THREAD

**Issue by robertabcd** [robertabcd/PttChrome#13]
Fonts and other images in compiled css look like:
```
@font-face {
  font-family: SymMingLiu;
  src: url(assets/symmingliu.aaa394dd81dbe129da06687a75bfe002.woff)
}
```
The url should be relative to the css file, so it shouldn't have `assets/` prefix.

[resolve-url-loader](https://www.npmjs.com/package/resolve-url-loader) seems to be advertising to do the trick but I can't make it to work.

A quick workaround on the server side can be implemented fairly easily.

**Comment by tomchentw** [comment]
@robertabcd I can try fixing this.
