### ISSUE TITLE
plz add auto login function

### ISSUE THREAD

**Issue by jaxon0523** [robertabcd/PttChrome#17]
as title thx a lot
plz!!!

**Comment by fhoshino** [comment]
It seems even the original autologin function (hidden) has been removed from the latest update

Uncaught ReferenceError: pttchrome is not defined
    at eval (eval at <anonymous> (:2:479), <anonymous>:20:33)

**Comment by tomchentw** [comment]
@fhoshino hey, I removed it in #16. Could you point out which function do the auto-login stuff?

**Comment by fhoshino** [comment]
I guess the latest update removed pttchrome keyword broke this script, 
https://greasyfork.org/en/scripts/35360-term-ptt-autologin

**Comment by robertabcd** [comment]
3rd party scripts are not supported.

**Comment by hdd60311** [comment]
所以說網頁版客戶端能否內建支持自動登入?實在希望能有這功能不然每次都要手動輸入

**Comment by fhoshino** [comment]
script 更新了

**Comment by maple3142** [comment]
弄了一個使用不同方法來自動登入的腳本
https://greasyfork.org/zh-TW/scripts/368445-term-ptt-cc-%E8%87%AA%E5%8B%95%E7%99%BB%E5%85%A5
