### ISSUE TITLE
若干bug/限制希望能修復

### ISSUE THREAD

**Issue by hdd60311** [robertabcd/PttChrome#18]
~~1. 開啟滑鼠瀏覽下左鍵點擊連結沒有效果(已解決)~~
2. 貼上操作開放使用滑鼠執行
3. 滑鼠瀏覽底色設定問題
4. 內建自動登入功能(如果做得到的話)

**Comment by kivx** [comment]
您好，滑鼠瀏覽底色效果功能好像失效了唷！

**Comment by hdd60311** [comment]
目前變成強制顯示滑鼠瀏覽底色效果了，設定裡沒勾選也一樣顯示

**Comment by robertabcd** [comment]
@hdd60311 請問是使用哪個瀏覽器？我目前測試用 Chrome、Firefox、Safari 都可以正常切換。

**Comment by kivx** [comment]
1. 我用Firefox，似乎底色是強制的，無法關。
2. PTT頁面用Pageup/Pagedown切換時，會有短暫亂碼出現，不確定是不是個案。

**Comment by yjlintw** [comment]
只是要達成自動登入的話，可能可以用localstorage來達成，但是應該不太安全

**Comment by hdd60311** [comment]
我這邊試過firefox和chrome都一樣強制顯示底色，而且也都一樣強制綠色無法調整成其他色

**Comment by tomchentw** [comment]
@hdd60311 方便發個截圖看看？謝啦

**Comment by hdd60311** [comment]
![1](https://user-images.githubusercontent.com/5089290/34675963-23710080-f4c6-11e7-8c9f-537772c6e6e9.png)
![2](https://user-images.githubusercontent.com/5089290/34675964-239c6608-f4c6-11e7-91e1-468e6e44f652.png)
補充一點在firefox上顏色設定顯示是直接鎖死在藍色，點其他任何顏色顯示都不會變
![3](https://user-images.githubusercontent.com/5089290/34676123-c113a7ac-f4c6-11e7-89a5-c7d281e6bd3b.png)

**Comment by kivx** [comment]
1. Firefox的滑鼠瀏覽底色，在設定中的確是鎖死在藍色，而實際瀏覽是綠色。
2. 如果開啟END推文即時更新，瀏覽文章時END功能似乎是不能用的？

**Comment by tomchentw** [comment]
@hdd60311 你可以試試「右鍵>滑鼠瀏覽」看是否此選項有勾選？若有，取消勾選之後應該就不會出現底色了？

**Comment by hdd60311** [comment]
取消勾選滑鼠瀏覽自然是不會有底色但這不是問題癥結所在吧

**Comment by kivx** [comment]
剛發現開啟滑鼠瀏覽時，使用PageUp/PageDown切換頁面時會有短暫亂碼出現
關掉滑鼠瀏覽功能就正常。

**Comment by IepIweidieng** [comment]
這個「藍色」(#3399ff) 似乎是文字選取的反白顏色。因爲設定中並沒有這個顏色。

解決方式應該是避免在選擇顏色時出現反白顏色。

> 補充一點在firefox上顏色設定顯示是直接鎖死在藍色，點其他任何顏色顯示都不會變 ![3](https://user-images.githubusercontent.com/5089290/34676123-c113a7ac-f4c6-11e7-89a5-c7d281e6bd3b.png)
