### ISSUE TITLE
Basic support for iOS + external keyboard

### ISSUE THREAD

**Issue by denkeni** [robertabcd/PttChrome#34]
Arrow keys are crucial in PTT experience. Currently it's not possible to use arrow keys on iOS, even with external keyboard. A possible simple fix for external keyboard is described below:

Here's a table of crucial keys for PTT, properties of KeyboardEvent, verified on iOS 11.2.5 Safari:

|               | `key`                                 | `keyCode` |
| -------- |:------------------------:| -----------:|
| ↑            | UIKeyInputTopArrow       |       0          |
| ↓            | UIKeyInputBottomArrow |       0          |
| ←            | UIKeyInputLeftArrow       |       0         |
| →            | UIKeyInputRightArrow     |       0         |
| control   | Dead                                  |       0        |

Currently it looks impossible to identify "control" and combination keys. We'll focus on arrow keys below.

Issue 1: `keyCode`
[This line of code](https://github.com/robertabcd/PttChrome/blob/40a8fa236fe4cde0358586cee3ccb6edbe0f70e0/src/js/term_view.js#L155) filtered out all of those keys. Since `keyCode` is deprecated, `key` should be preferred (ref: [KeyboardEvent](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent), [Example code](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode#Example)).

Issue 2: `key` value
Sadly, iOS does not return [standard `key` value](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values#Navigation_keys) (but macOS does). However, it's still possible to simply add those `key` values listed above to corresponding standard values, ex. [`case 'ArrowLeft'`](https://github.com/robertabcd/PttChrome/blob/4874cafab97f22c32cbdb3935e759221cc4fc94c/src/js/term_keyboard.js#L63) along with `case 'UIKeyInputLeftArrow'`.

**Comment by robertabcd** [comment]
I just tested with iPadOS 13.2.2 and Smart Keyboard Folio. It does work for me. Please reopen this and provide more info if it is still not working for you at iPadOS 13+.
