### ISSUE TITLE
滑鼠滾輪操作失效

### ISSUE THREAD

**Issue by hdd60311** [robertabcd/PttChrome#45]
https://www.ptt.cc/bbs/Browsers/M.1530547504.A.017.html

**Comment by hdd60311** [comment]
@robertabcd 能盡快處理一下嗎，現在不能用滾輪實在不太方便

**Comment by robertabcd** [comment]
Looks like it was accidentally removed in 9f629abb6320017b27a74bda08fbc7c2abe7d0d9.

**Comment by robertabcd** [comment]
Duplicate of #35
