### ISSUE TITLE
支持用滑鼠執行貼上操作

### ISSUE THREAD

**Issue by hdd60311** [robertabcd/PttChrome#46]
如標題，已經等這個很久了

**Comment by robertabcd** [comment]
This is currently not possible due to major browsers disallowing reading clipboard (or doing paste) programmatically. The only way to trigger it is through shortcut key.

**Comment by robertabcd** [comment]
Async clipboard API is enabled by default under Chrome 66+.
Implemented in 51714f4bb95ddae2b337822df0155c93678a5e3d.

**Comment by hdd60311** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1461465
firefox在63也改進了Async clipboard API但剛升上63版試了下還是無法用滑鼠貼上?
