### ISSUE TITLE
和瀏覽器的密碼管理員整合

### ISSUE THREAD

**Issue by timdream** [robertabcd/PttChrome#66]
實作會有點複雜，要在 PTT 出現「輸入密碼」的文字的時候貼一個 `<input type="password">` 在游標的位置，且把 focus 從隱形的 `<input>` 移過去。總之先開 issue 建議一下，感謝。

**Comment by timdream** [comment]
@robertabcd 請問發PR的話願意收嗎？

想了一下，要實作有一些技術限制：要偵測 PTT 的進站畫面與修改密碼畫面，但文章一定可以 spoof這些輸出。要事先對這些技術限制有共識，才值得開始開發。

**Comment by robertabcd** [comment]
我覺得應該設計在 websocket 連線裡，不希望再增加直接 parse terminal 內文字的功能。
