### ISSUE TITLE
Live文小幫手失效

### ISSUE THREAD

**Issue by holishing** [robertabcd/PttChrome#99]
轉自: [#1XThzXVK (PttBug) [ptt.cc]](https://www.ptt.cc/bbs/PttBug/M.1635172193.A.7D4.html)

回報內容:
> 如題，term.ptt.cc（以下簡稱term）是基於PttChrome製作而成的支援wss版本
> 而PttChrome內有一個「Live文小幫手」也被繼承過來
> 簡單來說它是一個可以在Live文中自動更新推文的小功能（最短可到1秒/次）
> 在收看特定直播（例如每日疫情記者會、電競比賽、三金頒獎）等狀況下很好用
>
> 但是，在term這邊的這個功能雖然有在右鍵功能表以及設定中顯示出來
> 實際上卻是無法使用，點選後毫無反應，一樣不會自動更新推文
> 而PTT網頁版雖然有自動更新推文並捲動的功能，但也早就故障許久未修
> 前往term的GitHub也可以發現最後一次commit已是去年4月
> 所以想在此同時請教：這個軟體及站點是否已經處於abandoned狀態...？
>
> 以上bug回報，問題的部分也同時希望有人可解答！

**Comment by IepIweidieng** [comment]
根據 robertabcd/PttChrome@8e52f4bbd6f65a5b974585cd05edd9d13d543662 的 commit 訊息，此分支似乎已解決此問題。

**Comment by holishing** [comment]
感謝確認，那我回去原文註記一下:)
